{
  "solidity": "0.8.20",
  "settings": {
    "optimizer": {
      "enabled": true,
      "runs": 200
    },
    "remappings": [
      "@foundry-rs/forge-std/=lib/forge-std/",
      "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
    ]
  }
}
